"""
Build src/expense_tracker/_fonts.py: the dashboard's three OFL fonts, subset to Latin
and inlined as base64 WOFF2, so the page needs no external requests.

Fonts (all SIL Open Font License 1.1, from github.com/google/fonts):
  Fraunces (headlines, numbers, italic notes), Figtree (UI text), DM Mono (labels, amounts).

Usage:
    pip install fonttools brotli
    python scripts/build_fonts.py
"""

import base64
import io
import tempfile
import urllib.request
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

SOURCE = "https://raw.githubusercontent.com/google/fonts/main/ofl/"
OUT = Path(__file__).resolve().parent.parent / "src" / "expense_tracker" / "_fonts.py"

# Basic Latin, Latin-1 punctuation and the few typographic symbols the page uses
UNICODES = (
    list(range(0x20, 0x7F))
    + [0xA0, 0xA3, 0xA7, 0xA9, 0xB7, 0xD7, 0xE9]
    + [0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2022, 0x2026, 0x2039, 0x203A, 0x20AC, 0x2212, 0x2713]
)

# (family, style, url path, axis limits, css weight range)
FONTS = [
    ("Fraunces", "normal", "fraunces/Fraunces%5BSOFT,WONK,opsz,wght%5D.ttf",
     {"SOFT": 0, "WONK": 0, "opsz": 48, "wght": (400, 600)}, "400 600"),
    ("Fraunces", "italic", "fraunces/Fraunces-Italic%5BSOFT,WONK,opsz,wght%5D.ttf",
     {"SOFT": 0, "WONK": 0, "opsz": 36, "wght": (400, 500)}, "400 500"),
    ("Figtree", "normal", "figtree/Figtree%5Bwght%5D.ttf", {"wght": (400, 600)}, "400 600"),
    ("DM Mono", "normal", "dmmono/DMMono-Regular.ttf", None, "400"),
    ("DM Mono", "normal", "dmmono/DMMono-Medium.ttf", None, "500"),
]  # fmt: skip


def build_face(url_path: str, limits: dict | None, cache: Path) -> bytes:
    local = cache / url_path.replace("/", "_").replace("%5B", "[").replace("%5D", "]")
    if not local.exists():
        urllib.request.urlretrieve(SOURCE + url_path, local)  # noqa: S310 - fixed https URL
    font = TTFont(local)
    if limits:
        font = instancer.instantiateVariableFont(font, limits)
    options = subset.Options()
    options.flavor = "woff2"
    options.layout_features = ["kern", "liga", "lnum", "tnum", "pnum"]
    options.name_IDs = ["*"]
    subsetter = subset.Subsetter(options)
    subsetter.populate(unicodes=UNICODES)
    subsetter.subset(font)
    buf = io.BytesIO()
    font.flavor = "woff2"
    font.save(buf)
    return buf.getvalue()


def main() -> None:
    faces = []
    total = 0
    with tempfile.TemporaryDirectory() as tmp:
        for family, style, url_path, limits, weight in FONTS:
            data = build_face(url_path, limits, Path(tmp))
            total += len(data)
            b64 = base64.b64encode(data).decode()
            faces.append(
                f"@font-face{{font-family:'{family}';font-style:{style};font-weight:{weight};"
                f"font-display:swap;src:url(data:font/woff2;base64,{b64}) format('woff2')}}"
            )
            print(f"{family} {style} {weight}: {len(data) / 1024:.0f} KB")

    css = "\n".join(faces)
    OUT.write_text(
        '"""Generated by scripts/build_fonts.py: Fraunces, Figtree and DM Mono (SIL OFL 1.1), Latin subset."""\n\n'
        f"FONT_CSS = {css!r}\n",
        encoding="utf-8",
    )
    print(f"Wrote {OUT} ({total / 1024:.0f} KB of WOFF2)")


if __name__ == "__main__":
    main()
